version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      # Install JQ to process JSON from now-no-alias
      -run: sudo apt-get install jq

      # Install Zeit Now
      - run: sudo yarn global add now now-no-alias

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn coverage:report

      # Zeit Now deployment
      - run: now -t ${NOW_TOKEN} --public
      - run: now alias -t ${NOW_TOKEN}
      - run: now rm -t ${NOW_TOKEN} $(now-no-alias | jq -r '.[] | .uid') -y
